# Generated by Django 5.0.3 on 2024-03-17 12:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ColumnType',
            fields=[
                ('columnTypeID', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Files',
            fields=[
                ('fileID', models.AutoField(primary_key=True, serialize=False)),
                ('path', models.FileField(upload_to='store/files/')),
            ],
        ),
        migrations.CreateModel(
            name='Column',
            fields=[
                ('columnID', models.AutoField(primary_key=True, serialize=False)),
                ('column_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.columntype')),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.files')),
            ],
        ),
    ]
