# Generated by Django 5.0.3 on 2024-03-17 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='files',
            old_name='path',
            new_name='content',
        ),
    ]
