# Generated by Django 5.0.3 on 2024-03-18 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_files_fileupload'),
    ]

    operations = [
        migrations.AddField(
            model_name='column',
            name='name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
