# Generated by Django 5.0.3 on 2024-03-18 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_column_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='column',
            name='column_type',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='ColumnType',
        ),
    ]
